name: CI

on:
  pull_request:
    branches:
      - main

env:
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Run Clippy
        run: cargo clippy --all-features --all-targets
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release --all-features
      - name: Format
        run: cargo fmt -v --all --check
